apiVersion: v1
kind: Service
metadata:
  name: __CI_PROJECT_NAME__
  namespace: __NAMESPACE__
  labels:
    name: __CI_PROJECT_NAME__
spec:
  type: ClusterIP
  selector:
    name: __CI_PROJECT_NAME__
  ports:
    - name: http
      port: __PORT__
      targetPort: __PORT__
